# Generated by Django 3.1.2 on 2020-10-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longitude', models.FloatField()),
                ('Latitude', models.FloatField()),
                ('Unique_Squirrel_ID', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Shift', models.CharField(blank=True, max_length=100)),
                ('Age', models.CharField(blank=True, max_length=100)),
                ('Primary_Fur_Color', models.CharField(blank=True, max_length=100)),
                ('Location', models.CharField(blank=True, max_length=100)),
                ('Specific_Location', models.CharField(blank=True, max_length=100)),
                ('Running', models.BooleanField(blank=True, null=True)),
                ('Chasing', models.BooleanField(blank=True, null=True)),
                ('Climbing', models.BooleanField(blank=True, null=True)),
                ('Eating', models.BooleanField(blank=True, null=True)),
                ('Foraging', models.BooleanField(blank=True, null=True)),
                ('Other_Activities', models.CharField(blank=True, max_length=100)),
                ('Kuks', models.BooleanField(blank=True, null=True)),
                ('Quaas', models.BooleanField(blank=True, null=True)),
                ('Moans', models.BooleanField(blank=True, null=True)),
                ('Tail_Flags', models.BooleanField(blank=True, null=True)),
                ('Tail_Twitches', models.BooleanField(blank=True, null=True)),
                ('Approaches', models.BooleanField(blank=True, null=True)),
                ('Indifferent', models.BooleanField(blank=True, null=True)),
                ('Runs_From', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
